@echo off
REM ================================================================
REM D3D9 Frame Trace Proxy - Build Script (MSVC x86, WITH CRT)
REM
REM Prerequisites:
REM   - Visual Studio with C++ desktop workload
REM   - d3d9_trace_hooks.inc generated by:
REM       python -m graphics.directx.dx9.tracer codegen -o d3d9_trace_hooks.inc
REM
REM Output: d3d9.dll copied to ../bin/
REM ================================================================

REM Auto-find Visual Studio via vswhere
for /f "tokens=*" %%i in ('"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath 2^>nul') do set VSDIR=%%i

if not defined VSDIR (
    echo ERROR: Visual Studio not found. Install VS Build Tools.
    exit /b 1
)

set VCVARSALL=%VSDIR%\VC\Auxiliary\Build\vcvarsall.bat
if not exist "%VCVARSALL%" (
    echo ERROR: vcvarsall.bat not found at %VCVARSALL%
    exit /b 1
)

if not exist "d3d9_trace_hooks.inc" (
    echo ERROR: d3d9_trace_hooks.inc not found.
    echo Run: python -m graphics.directx.dx9.tracer codegen -o d3d9_trace_hooks.inc
    exit /b 1
)

echo Setting up x86 build environment...
call "%VCVARSALL%" x86 >nul 2>&1

echo.
echo Compiling d3d9_trace_main.c...
cl.exe /nologo /O2 /W3 /c /D "WIN32" /D "NDEBUG" d3d9_trace_main.c
if errorlevel 1 goto :error

echo Compiling d3d9_trace_wrapper.c...
cl.exe /nologo /O2 /W3 /c /D "WIN32" /D "NDEBUG" d3d9_trace_wrapper.c
if errorlevel 1 goto :error

echo Compiling d3d9_trace_device.c...
cl.exe /nologo /O2 /W3 /c /D "WIN32" /D "NDEBUG" d3d9_trace_device.c
if errorlevel 1 goto :error

echo Linking d3d9.dll...
link.exe /nologo /DLL /DEF:d3d9.def /OUT:d3d9.dll d3d9_trace_main.obj d3d9_trace_wrapper.obj d3d9_trace_device.obj kernel32.lib user32.lib
if errorlevel 1 goto :error

echo.
echo === Build successful ===
echo.

REM Copy output to bin/
copy /Y d3d9.dll ..\bin\d3d9.dll >nul
echo Deployed d3d9.dll to bin/

echo Deploy: copy bin/d3d9.dll and bin/proxy.ini to your target application directory.
echo Trigger capture: create file 'dxtrace_capture.trigger' in the target dir.
echo Output: dxtrace_frame.jsonl

REM Clean intermediates
del *.obj *.lib *.exp d3d9.dll 2>nul

exit /b 0

:error
echo.
echo === BUILD FAILED ===
exit /b 1
