rtx.antiCulling.light.fovScale = 2
rtx.antiCulling.light.enable = False
rtx.fallbackLightMode = 1
rtx.enableNearPlaneOverride = True
rtx.antiCulling.object.hashInstanceWithBoundingBoxHash = False
rtx.geometryAssetHashRuleString = positions,indices,texcoords,geometrydescriptor
rtx.fallbackLightRadiance = 5, 5, 5
rtx.useVertexCapture = True
rtx.nearPlaneOverride = 0.1
rtx.antiCulling.light.numFramesToExtendLightLifetime = 60
rtx.geometryGenerationHashRuleString = positions,indices,texcoords,geometrydescriptor,vertexlayout,vertexshader
rtx.enableRaytracing = True
rtx.debugView.composite.compositeViewIdx = 0
rtx.enableReplacementAssets = True
rtx.useWorldMatricesForShaders = True
rtx.terrain.terrainAsDecalsEnabledIfNoBaker = True
rtx.captureInstances = True
rtx.antiCulling.object.fovScale = 1.5
rtx.antiCulling.object.enable = False
rtx.debugView.debugViewIdx = 0
rtx.remixMenuKeyBinds = X
rtx.skyBoxTextures = 0x443B45FB9971FC90, 0x78AD1D0EDA0FFC21, 0x8405ADDE0AE29A5F
rtx.antiCulling.object.enableHighPrecisionAntiCulling = False
rtx.terrain.terrainAsDecalsAllowOverModulate = False
rtx.fallbackLightDirection = -70.5, -70.5, -70.5
rtx.qualityDLSS = 2
rtx.zUp = True
rtx.orthographicIsUI = True
rtx.fusedWorldViewMode = 0
rtx.skyBrightness = 0.01
rtx.antiCulling.object.numObjectsToKeep = 1000
rtx.captureShowMenuOnHotkey = False
rtx.sceneScale = 0.0001
rtx.terrainBaker.enableBaking = False
rtx.uiTextures = 0x03016D2FBBF5C65D, 0x2164293A60D148AC
