rtx.debugView.debugViewIdx = 0
rtx.remixMenuKeyBinds = X
rtx.geometryAssetHashRuleString = indices,texcoords,geometrydescriptor
rtx.fallbackLightRadiance = 3, 0.3, 0.3
rtx.useVertexCapture = True
rtx.fallbackLightMode = 1
rtx.captureInstances = True
rtx.debugView.composite.compositeViewIdx = 0
rtx.terrain.terrainAsDecalsEnabledIfNoBaker = True
rtx.skyBoxTextures = 0x443B45FB9971FC90, 0x78AD1D0EDA0FFC21, 0x8405ADDE0AE29A5F
rtx.terrain.terrainAsDecalsAllowOverModulate = False
rtx.fallbackLightDirection = -70.5, 1.5, -326.9
rtx.zUp = True
rtx.fusedWorldViewMode = 0
rtx.skyBrightness = 0.01
rtx.sceneScale = 0.0001
rtx.terrainBaker.enableBaking = False
rtx.enableRaytracing = True
rtx.enableReplacementAssets = True
rtx.uiTextures = 0x03016D2FBBF5C65D, 0x2164293A60D148AC
