#!/usr/bin/env python3
"""Declarative ASI patch builder.

Generates a zero-CRT Windows DLL (.asi) from a JSON patch specification.
The caller must locate vcvarsall.bat and pass it as a required argument;
this tool does no toolchain discovery of its own.

Commands:

  build   Generate C source from spec, compile + link via MSVC.
  show    Print the generated C source to stdout (no compilation).
  init    Create a skeleton spec.json in a new directory.

Finding vcvarsall.bat (run once, reuse the path):

  vswhere -latest -property installationPath
  # append: \\VC\\Auxiliary\\Build\\vcvarsall.bat

Examples:

  python retools/asi_patcher.py build spec.json \\
      --vcvarsall "C:\\Program Files\\...\\vcvarsall.bat"

  python retools/asi_patcher.py show spec.json

  python retools/asi_patcher.py init patches/my_game/

Spec format (JSON):

  {
    "name": "MyPatch",          <-- valid C identifier, used for output filename
    "arch": "x86",              <-- "x86" or "x64"
    "base": "0x400000",         <-- optional: PE preferred base for ASLR rebase
    "description": "optional human-readable note",
    "verify": [
      {"addr": "0x401000", "expect": "55 8B EC"}
    ],
    "patches": [
      {"name": "Gate",  "type": "bytes", "addr": "0x401000", "data": "B0 01 C3"},
      {"name": "Fill",  "type": "nop",   "addr": "0x402000", "count": 6},
      {"name": "Dist",  "type": "float", "addr": "0x403000", "value": 99999.0},
      {"name": "Mul",   "type": "double","addr": "0x404000", "value": 1.0e12},
      {"name": "Flag",  "type": "int32", "addr": "0x405000", "value": -1},
      {"name": "Big",   "type": "int64", "addr": "0x406000", "value": 0}
    ]
  }

When "base" is present, all addresses in verify/patches are treated as
static VAs relative to the preferred image base.  At runtime the ASI
resolves the actual module base via GetModuleHandleA(NULL) and rebases
every address to (runtime_base + addr - preferred_base).  Omit "base"
for non-ASLR binaries where addresses are absolute.

Patch types: bytes, code, nop, float, double, int32, int64
("code" is an alias for "bytes")
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


# ── Spec loading & validation ───────────────────────────────────────────

_C_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_PATCH_TYPES = frozenset(("bytes", "code", "nop", "float",
                          "double", "int32", "int64"))


def _load_spec(path: Path) -> dict:
    with open(path) as f:
        spec = json.load(f)

    name = spec.get("name", "")
    if not _C_IDENT.match(name):
        raise SystemExit(
            f"spec.name must be a valid C identifier, got {name!r}"
        )

    arch = spec.setdefault("arch", "x86")
    if arch not in ("x86", "x64"):
        raise SystemExit(f"spec.arch must be x86 or x64, got {arch!r}")

    spec.setdefault("verify", [])
    spec.setdefault("patches", [])

    for p in spec["patches"]:
        pn = p.get("name", "")
        if not _C_IDENT.match(pn):
            raise SystemExit(
                f"Patch name must be a valid C identifier, got {pn!r}"
            )
        if p.get("type") not in _PATCH_TYPES:
            raise SystemExit(
                f"Unknown patch type {p.get('type')!r} in {pn!r}"
            )

    return spec


# ── Helpers ─────────────────────────────────────────────────────────────


def _hex_to_c(hex_str: str) -> str:
    """'B0 01 C2' -> '0xB0, 0x01, 0xC2'"""
    return ", ".join(f"0x{t}" for t in hex_str.strip().split())


def _c_addr(addr_str: str, arch: str, base: int | None = None) -> str:
    val = int(addr_str, 16)
    if base is not None:
        if val < base:
            raise ValueError(
                f"address 0x{val:X} is below image base 0x{base:X}"
            )
        rva = val - base
        d = 16 if arch == "x64" else 8
        return f"rva(0x{rva:0{d}X})"
    d = 16 if arch == "x64" else 8
    return f"(UINT_PTR)0x{val:0{d}X}"


# ── C code generation ───────────────────────────────────────────────────


def generate_c(spec: dict) -> str:  # noqa: C901 — long but linear
    arch = spec["arch"]
    name = spec["name"]
    desc = spec.get("description", "")
    patches = spec["patches"]
    verifies = spec["verify"]
    base: int | None = None
    if "base" in spec:
        base = int(spec["base"], 16) if isinstance(spec["base"], str) else spec["base"]

    L: list[str] = []

    def w(s: str = "") -> None:
        L.append(s)

    # header
    w(f"/* Auto-generated ASI patch: {name}  ({arch}) */")
    if desc:
        for dl in desc.splitlines():
            w(f"/* {dl} */")
    w("/* Generated by retools/asi_patcher.py */")
    w()
    w("#define WIN32_LEAN_AND_MEAN")
    w("#include <windows.h>")
    w()
    w('#pragma comment(lib, "kernel32.lib")')
    w("int _fltused = 0;")
    w()

    if base is not None:
        w("static UINT_PTR g_base;")
        w()
        w("static UINT_PTR rva(UINT_PTR offset)")
        w("{")
        w("    return g_base + offset;")
        w("}")
        w()

    # byte helpers
    w("static void write_mem(volatile unsigned char *dst,")
    w("                      const unsigned char *src, unsigned int len)")
    w("{")
    w("    unsigned int i;")
    w("    for (i = 0; i < len; i++) dst[i] = src[i];")
    w("}")
    w()
    w("static void fill_nop(volatile unsigned char *dst, unsigned int len)")
    w("{")
    w("    unsigned int i;")
    w("    for (i = 0; i < len; i++) dst[i] = 0x90;")
    w("}")
    w()

    # VirtualProtect wrappers
    w("static int patch_bytes(UINT_PTR addr, const unsigned char *data,")
    w("                       unsigned int len)")
    w("{")
    w("    DWORD old;")
    w("    if (!VirtualProtect((void *)addr, len, PAGE_EXECUTE_READWRITE, &old))")
    w("        return 0;")
    w("    write_mem((unsigned char *)addr, data, len);")
    w("    VirtualProtect((void *)addr, len, old, &old);")
    w("    return 1;")
    w("}")
    w()
    w("static int patch_nop(UINT_PTR addr, unsigned int len)")
    w("{")
    w("    DWORD old;")
    w("    if (!VirtualProtect((void *)addr, len, PAGE_EXECUTE_READWRITE, &old))")
    w("        return 0;")
    w("    fill_nop((unsigned char *)addr, len);")
    w("    VirtualProtect((void *)addr, len, old, &old);")
    w("    return 1;")
    w("}")
    w()

    # logging
    w("static HANDLE g_log = INVALID_HANDLE_VALUE;")
    w()
    w("static void log_open(void)")
    w("{")
    w("    char path[MAX_PATH];")
    w("    GetModuleFileNameA(NULL, path, MAX_PATH);")
    w("    {")
    w("        char *slash = path, *p = path;")
    w("        while (*p) { if (*p == '\\\\' || *p == '/') slash = p; p++; }")
    w("        slash[1] = '\\0';")
    w("    }")
    w("    {")
    w(f'        const char nm[] = "{name}.log";')
    w("        char *dst = path;")
    w("        const char *src;")
    w("        while (*dst) dst++;")
    w("        src = nm;")
    w("        while (*src) *dst++ = *src++;")
    w("        *dst = '\\0';")
    w("    }")
    w("    g_log = CreateFileA(path, GENERIC_WRITE, FILE_SHARE_READ, NULL,")
    w("                        CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);")
    w("}")
    w()
    w("static void log_str(const char *s)")
    w("{")
    w("    DWORD n;")
    w("    const char *p;")
    w("    if (g_log == INVALID_HANDLE_VALUE) return;")
    w("    p = s;")
    w("    while (*p) p++;")
    w("    WriteFile(g_log, s, (DWORD)(p - s), &n, NULL);")
    w("}")
    w()

    if arch == "x86":
        w("static void log_hex(UINT_PTR v)")
        w("{")
        w("    char buf[11];")
        w('    const char hex[] = "0123456789ABCDEF";')
        w("    buf[0] = '0'; buf[1] = 'x';")
        w("    buf[2]  = hex[(v >> 28) & 0xF]; buf[3] = hex[(v >> 24) & 0xF];")
        w("    buf[4]  = hex[(v >> 20) & 0xF]; buf[5] = hex[(v >> 16) & 0xF];")
        w("    buf[6]  = hex[(v >> 12) & 0xF]; buf[7] = hex[(v >>  8) & 0xF];")
        w("    buf[8]  = hex[(v >>  4) & 0xF]; buf[9] = hex[v & 0xF];")
        w("    buf[10] = '\\0';")
        w("    log_str(buf);")
        w("}")
    else:
        w("static void log_hex(UINT_PTR v)")
        w("{")
        w("    char buf[19];")
        w('    const char hex[] = "0123456789ABCDEF";')
        w("    int i;")
        w("    buf[0] = '0'; buf[1] = 'x';")
        w("    for (i = 0; i < 16; i++)")
        w("        buf[2 + i] = hex[(v >> (60 - i * 4)) & 0xF];")
        w("    buf[18] = '\\0';")
        w("    log_str(buf);")
        w("}")
    w()

    w("static void log_patch(const char *name, UINT_PTR addr, int ok)")
    w("{")
    w('    log_str(ok ? "[OK]   " : "[FAIL] ");')
    w("    log_str(name);")
    w('    log_str(" @ ");')
    w("    log_hex(addr);")
    w('    log_str("\\r\\n");')
    w("}")
    w()
    w("static void log_flush(void)")
    w("{")
    w("    if (g_log != INVALID_HANDLE_VALUE) FlushFileBuffers(g_log);")
    w("}")
    w()
    w("static void log_close(void)")
    w("{")
    w("    if (g_log != INVALID_HANDLE_VALUE) CloseHandle(g_log);")
    w("    g_log = INVALID_HANDLE_VALUE;")
    w("}")
    w()

    # verify
    w("static int verify_exe(void)")
    w("{")
    if not verifies:
        w("    return 1;")
    else:
        for v in verifies:
            addr = _c_addr(v["addr"], arch, base)
            tokens = v["expect"].strip().split()
            cnt = len(tokens)
            arr = ", ".join(f"0x{t}" for t in tokens)
            w("    {")
            w(f"        const unsigned char expect[] = {{ {arr} }};")
            w(f"        if (IsBadReadPtr((void *){addr}, {cnt}))")
            w("            return 0;")
            w("        {")
            w(f"            const unsigned char *p = (const unsigned char *){addr};")
            w("            unsigned int i;")
            w(f"            for (i = 0; i < {cnt}; i++)")
            w("                if (p[i] != expect[i]) return 0;")
            w("        }")
            w("    }")
        w("    return 1;")
    w("}")
    w()

    # individual patch functions
    for p in patches:
        pn = p["name"]
        pt = p["type"]
        addr = _c_addr(p["addr"], arch, base)

        w(f"static int apply_{pn}(void)")
        w("{")

        if pt in ("bytes", "code"):
            tokens = p["data"].strip().split()
            if len(tokens) > 12:
                w("    const unsigned char data[] = {")
                for ci in range(0, len(tokens), 12):
                    chunk = tokens[ci : ci + 12]
                    tail = "," if ci + 12 < len(tokens) else ""
                    w(f"        {', '.join(f'0x{t}' for t in chunk)}{tail}")
                w("    };")
            else:
                w(f"    const unsigned char data[] = {{ {_hex_to_c(p['data'])} }};")
            w(f"    return patch_bytes({addr}, data, sizeof(data));")

        elif pt == "nop":
            w(f"    return patch_nop({addr}, {p['count']});")

        elif pt == "float":
            w(f"    float v = {p['value']}f;")
            w(f"    return patch_bytes({addr}, (const unsigned char *)&v, sizeof(v));")

        elif pt == "double":
            w(f"    double v = {p['value']};")
            w(f"    return patch_bytes({addr}, (const unsigned char *)&v, sizeof(v));")

        elif pt == "int32":
            w(f"    int v = {p['value']};")
            w(f"    return patch_bytes({addr}, (const unsigned char *)&v, sizeof(v));")

        elif pt == "int64":
            w(f"    long long v = {p['value']}LL;")
            w(f"    return patch_bytes({addr}, (const unsigned char *)&v, sizeof(v));")

        w("}")
        w()

    # DllMain
    w("BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID lpReserved)")
    w("{")
    w("    (void)lpReserved;")
    w("    if (reason != DLL_PROCESS_ATTACH)")
    w("        return TRUE;")
    w("    DisableThreadLibraryCalls(hModule);")

    if base is not None:
        w("    g_base = (UINT_PTR)GetModuleHandleA(NULL);")

    w("    log_open();")
    w(f'    log_str("{name} loaded\\r\\n");')

    if base is not None:
        w('    log_str("Base: "); log_hex(g_base); log_str("\\r\\n");')

    if verifies:
        w()
        w("    if (!verify_exe()) {")
        w('        log_str("verify FAILED -- wrong binary?\\r\\n");')
        w("        log_close();")
        w("        return TRUE;")
        w("    }")
        w('    log_str("verify OK\\r\\n");')

    w()
    for p in patches:
        pn = p["name"]
        addr = _c_addr(p["addr"], arch, base)
        w(f'    log_patch("{pn}", {addr}, apply_{pn}());')

    w()
    w('    log_str("All patches applied\\r\\n");')
    w("    log_flush();")
    w("    return TRUE;")
    w("}")
    w()

    return "\n".join(L)


# ── Build ───────────────────────────────────────────────────────────────


def cmd_build(spec_path: Path, vcvarsall: Path) -> None:
    spec = _load_spec(spec_path)
    arch = spec["arch"]
    name = spec["name"]
    out_dir = spec_path.parent.resolve()

    c_path = out_dir / "patch.c"
    obj_path = out_dir / "patch.obj"
    asi_path = out_dir / f"{name}.asi"

    c_path.write_text(generate_c(spec), encoding="utf-8")

    entry = "DllMain@12" if arch == "x86" else "DllMain"
    cmd = (
        f'call "{vcvarsall}" {arch} >nul 2>&1'
        f' && cl.exe /nologo /O1 /GS- /W3 /Zl'
        f' /D "WIN32" /D "NDEBUG"'
        f' /c /Fo"{obj_path}" "{c_path}"'
        f' && link.exe /nologo /DLL /NODEFAULTLIB'
        f' /ENTRY:{entry}'
        f' /OUT:"{asi_path}" "{obj_path}" kernel32.lib'
    )

    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if r.returncode != 0:
        print(r.stdout)
        print(r.stderr, file=sys.stderr)
        raise SystemExit(f"Build failed (exit {r.returncode})")

    # clean intermediates
    obj_path.unlink(missing_ok=True)
    (out_dir / f"{name}.lib").unlink(missing_ok=True)
    (out_dir / f"{name}.exp").unlink(missing_ok=True)

    size_kb = asi_path.stat().st_size / 1024
    print(f"[asi_patcher] OK  {asi_path}  ({size_kb:.1f} KB)")


def cmd_show(spec_path: Path) -> None:
    print(generate_c(_load_spec(spec_path)))


def cmd_init(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    spec_path = directory / "spec.json"
    if spec_path.exists():
        raise SystemExit(f"{spec_path} already exists")

    dir_name = re.sub(r"[^A-Za-z0-9_]", "_", directory.name)
    if not dir_name or not dir_name[0].isalpha():
        dir_name = "Patch_" + dir_name

    skeleton = {
        "name": dir_name,
        "arch": "x86",
        "base": "0x400000",
        "description": "",
        "verify": [],
        "patches": [],
    }
    spec_path.write_text(json.dumps(skeleton, indent=2) + "\n",
                         encoding="utf-8")
    print(f"[asi_patcher] Created {spec_path}")


# ── CLI ─────────────────────────────────────────────────────────────────


_BUILD_HELP = """\
Generate C source from a patch spec and compile it to a .asi plugin.

Requires the path to vcvarsall.bat so MSVC can be activated for the
target architecture (read from spec.arch).

To find vcvarsall.bat:

  vswhere -latest -property installationPath
  # then append: \\VC\\Auxiliary\\Build\\vcvarsall.bat

Example:

  python retools/asi_patcher.py build patches/game/spec.json \\
      --vcvarsall "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat"
"""


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = p.add_subparsers(dest="cmd")

    b = sub.add_parser(
        "build",
        help="Generate C + compile to .asi",
        description=_BUILD_HELP,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    b.add_argument("spec", type=Path,
                   help="Path to spec.json")
    b.add_argument("--vcvarsall", type=Path, required=True,
                   metavar="PATH",
                   help="Path to vcvarsall.bat  (see: vswhere -latest)")

    s = sub.add_parser("show",
                       help="Print generated C source to stdout")
    s.add_argument("spec", type=Path, help="Path to spec.json")

    i = sub.add_parser("init",
                       help="Create a skeleton spec.json in a directory")
    i.add_argument("directory", type=Path, help="Target directory")

    args = p.parse_args()
    if not args.cmd:
        p.print_help()
        raise SystemExit(1)

    if args.cmd == "build":
        cmd_build(args.spec, args.vcvarsall)
    elif args.cmd == "show":
        cmd_show(args.spec)
    elif args.cmd == "init":
        cmd_init(args.directory)


if __name__ == "__main__":
    main()
